import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/core/css/globals.css";
import { ClientProviders } from "@/core/providers/client-providers";
import { Navbar } from "@/core/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {/* <Navbar /> */}
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
